- .gitignore
- README.md
- setup.py
- tox.ini
Changes:
- Update `setup.py`.
- Setting `tox` for the unit test. (Excluded python3.7 because `typing.Literal` is new in python3.8.)
> Some changes before release.

- setup.py
Version update to v0.1.2
Omitted change of `python_requires` is fixed too.
> Version update to v0.1.2

- ain/utils.py
#12 
I misunderstood the behavior.
> Fix recovery calculation

- .gitignore
- setup.py
- tox.ini
Changes
- Support python3.6
- version up to 0.1.4
> Support python3.6 / version up to 0.1.4

- .gitignore
- ain/ain.py
- ain/ain_db/ref.py
- ain/net.py
- ain/provider.py
- ain/types.py
- ain/wallet.py
- requirements_dev.txt
- setup.py
- tests/data.py
- tests/test_ain.py
- tox.ini
Overall tests are the same as `ain-js`, but add python version suffix after the app name to make multi-version tests execute in the single blockchain.
> Add tests and fix errors

- README.md
- ain/ain.py
- ain/ain_db/ref.py
- ain/utils/__init__.py
- ain/wallet.py
- setup.py
- tests/test_ain.py
- tests/test_ain_utils.py
List of changes
- Update README.md
- Support SEC1
- Fix ref.py
- Implement stake functions
- Implement addFromV3Keystore and test
- Version up to 1.0.0
> Misc. updates before release 1.0.0

- .gitignore
- ain/ain.py
- ain/errors.py
- ain/provider.py
- ain/types.py
- ain/wallet.py
- tests/snapshots/snap_test_ain.py
- tests/snapshots/snap_test_ain_raw.py
- tests/test_ain.py
- tests/test_ain_raw.py
- tests/util.py
Support `rawResultMode=True` option.
* Related issue
ainblockchain/ain-blockchain#1053
> Support rawResultMode=True option

- ain/ain.py
- tests/test_ain.py
- tests/test_ain_raw.py
Add validateAppName and tests.
> Add validateAppName

- ain/ain.py
- ain/signer/__init__.py
- ain/signer/default_signer.py
- Update Signer abstract class for send transaction methods
- Update DefaultSigner class for send transaction methods
- https://github.com/ainblockchain/ain-js/issues/144 
Related PRs:
- https://github.com/ainblockchain/ain-js/pull/145
> Update Signer / DefaultSigner classes for send transaction methods

- setup.py
Merge PR for develop branch!
Related issues: 
- https://github.com/ainblockchain/ain-blockchain/issues/1253
> Merge v1.1.0 to develop branch

- .github/workflows/docs.yml
- https://github.com/ainblockchain/ain-py/issues/35
> Update docs.yml actions file to set python version

- ain/ain.py
- tests/test_ain.py
- Add methods for Transaction JSON RPC APIs
> Add methods for Transaction JSON RPC APIs

- ain/ain.py
- tests/test_ain.py
- Add methods for Block JSON RPC APIs
> Add methods for Block JSON RPC APIs

- ain/ain.py
- tests/test_ain.py
- Add missing methods for Blockchain Node JSON RPC APIs
> Add missing methods for Blockchain Node JSON RPC APIs

- ain/net.py
- tests/test_ain.py
- Add methods for Network JSON RPC APIs
> Add methods for Network JSON RPC APIs

- ain/net.py
- ain/provider.py
- tests/test_ain.py
- Add getPeerCandidateInfo() method
> Add getPeerCandidateInfo() method

- setup.py
> Release/v1.2.0 -> develop

- setup.py
> ain-py version update

- setup.py
update note
- typeing extention version update
> merge: master ← release

- ain/account.py
- ain/utils/__init__.py
- tests/data.py
- tests/snapshots/snap_test_ain.py
- tests/test_ain_account.py
- tests/test_ain_utils.py
- Support ETH derivation path in account generation from mnemonic
- Update test for the recent blockchain param (tx_bytes_limit) changes
- https://github.com/ainblockchain/ain-blockchain/issues/1282
> Support ETH derivation path for mnemonic
